version: '3.8'

services:
  postgres:
    container_name: auth-postgres
    image: postgres:13.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-misir}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-RhVZrV9qrZbB4zn5}
      POSTGRES_DB: ${POSTGRES_DB:-default}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres

volumes:
  postgres_data:
    external: false
